//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContactsWebService.ContactsSoap")]
    public interface ContactsSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> AddGroupAsync(string username, string password, string groupName, string Descriptions, bool showToChilds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGroups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<ContactsWebService.GroupsList[]> GetGroupsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> AddContactAsync(
                    string username, 
                    string password, 
                    string groupIds, 
                    string firstname, 
                    string lastname, 
                    string nickname, 
                    string corporation, 
                    string mobilenumber, 
                    string phone, 
                    string fax, 
                    System.DateTime birthdate, 
                    string email, 
                    byte gender, 
                    int province, 
                    int city, 
                    string address, 
                    string postalCode, 
                    System.DateTime additionaldate, 
                    string additionaltext, 
                    string descriptions);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContactsByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<ContactsWebService.GetContactsByIDResponse> GetContactsByIDAsync(ContactsWebService.GetContactsByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContacts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<ContactsWebService.ContactsGridList[]> GetContactsAsync(string username, string password, int groupId, string keyword, int from, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContactEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<ContactsWebService.ContactEventBL[]> GetContactEventsAsync(string username, string password, int contactId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckMobileExistInContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> CheckMobileExistInContactAsync(string username, string password, string mobileNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> ChangeContactAsync(
                    string username, 
                    string password, 
                    int contactId, 
                    string mobilenumber, 
                    string firstname, 
                    string lastname, 
                    string nickname, 
                    string corporation, 
                    string phone, 
                    string fax, 
                    string email, 
                    byte gender, 
                    int province, 
                    int city, 
                    string address, 
                    string postalCode, 
                    string additionaltext, 
                    string descriptions, 
                    int contactStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> RemoveContactAsync(string username, string password, string mobilenumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveContact2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> RemoveContact2Async(string username, string password, int contactId, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveContactByContactID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> RemoveContactByContactIDAsync(string username, string password, int contactId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> ChangeGroupAsync(string username, string password, int groupId, string groupName, string Descriptions, bool showToChilds, byte groupStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> RemoveGroupAsync(string username, string password, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddContactEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> AddContactEventsAsync(string username, string password, int contactId, string eventName, byte eventType, System.DateTime eventDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MergeGroups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> MergeGroupsAsync(string username, string password, int originGroupId, int destinationGroupId, bool deleteOriginGroup);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GroupsList
    {
        
        private int groupIDField;
        
        private int parentIdField;
        
        private int userIDField;
        
        private string groupNameField;
        
        private string groupDescriptionField;
        
        private byte groupStatusField;
        
        private int contactCountField;
        
        private bool showToChildField;
        
        private int childsCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int GroupID
        {
            get
            {
                return this.groupIDField;
            }
            set
            {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ParentId
        {
            get
            {
                return this.parentIdField;
            }
            set
            {
                this.parentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GroupName
        {
            get
            {
                return this.groupNameField;
            }
            set
            {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string GroupDescription
        {
            get
            {
                return this.groupDescriptionField;
            }
            set
            {
                this.groupDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public byte GroupStatus
        {
            get
            {
                return this.groupStatusField;
            }
            set
            {
                this.groupStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ContactCount
        {
            get
            {
                return this.contactCountField;
            }
            set
            {
                this.contactCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool ShowToChild
        {
            get
            {
                return this.showToChildField;
            }
            set
            {
                this.showToChildField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ChildsCount
        {
            get
            {
                return this.childsCountField;
            }
            set
            {
                this.childsCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContactsGridList
    {
        
        private int contactIDField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string nickNameField;
        
        private string corporationField;
        
        private string mobileNumbersField;
        
        private string faxNumberField;
        
        private string emailField;
        
        private byte genderField;
        
        private string descriptionsField;
        
        private System.DateTime createDateField;
        
        private string groupsField;
        
        private double creditField;
        
        private System.DateTime additionalDateField;
        
        private System.DateTime birthDateField;
        
        private int contactSortField;
        
        private byte contactStatusField;
        
        private string additionalTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ContactID
        {
            get
            {
                return this.contactIDField;
            }
            set
            {
                this.contactIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NickName
        {
            get
            {
                return this.nickNameField;
            }
            set
            {
                this.nickNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Corporation
        {
            get
            {
                return this.corporationField;
            }
            set
            {
                this.corporationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MobileNumbers
        {
            get
            {
                return this.mobileNumbersField;
            }
            set
            {
                this.mobileNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FaxNumber
        {
            get
            {
                return this.faxNumberField;
            }
            set
            {
                this.faxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public byte Gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Descriptions
        {
            get
            {
                return this.descriptionsField;
            }
            set
            {
                this.descriptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime CreateDate
        {
            get
            {
                return this.createDateField;
            }
            set
            {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Groups
        {
            get
            {
                return this.groupsField;
            }
            set
            {
                this.groupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public double Credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime AdditionalDate
        {
            get
            {
                return this.additionalDateField;
            }
            set
            {
                this.additionalDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int ContactSort
        {
            get
            {
                return this.contactSortField;
            }
            set
            {
                this.contactSortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public byte ContactStatus
        {
            get
            {
                return this.contactStatusField;
            }
            set
            {
                this.contactStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string AdditionalText
        {
            get
            {
                return this.additionalTextField;
            }
            set
            {
                this.additionalTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactEventBL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactsBL))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseBL
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContactEventBL : BaseBL
    {
        
        private int eventIDField;
        
        private int contactIDField;
        
        private string eventNameField;
        
        private byte eventTypeField;
        
        private System.DateTime eventDateField;
        
        private int eventDayField;
        
        private int eventMonthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int EventID
        {
            get
            {
                return this.eventIDField;
            }
            set
            {
                this.eventIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ContactID
        {
            get
            {
                return this.contactIDField;
            }
            set
            {
                this.contactIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EventName
        {
            get
            {
                return this.eventNameField;
            }
            set
            {
                this.eventNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public byte EventType
        {
            get
            {
                return this.eventTypeField;
            }
            set
            {
                this.eventTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime EventDate
        {
            get
            {
                return this.eventDateField;
            }
            set
            {
                this.eventDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int EventDay
        {
            get
            {
                return this.eventDayField;
            }
            set
            {
                this.eventDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int EventMonth
        {
            get
            {
                return this.eventMonthField;
            }
            set
            {
                this.eventMonthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContactsBL : BaseBL
    {
        
        private int contactIDField;
        
        private int userIDField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string corporationField;
        
        private string nickNameField;
        
        private string mobileNumbersField;
        
        private string phoneNumbersField;
        
        private string faxNumbersField;
        
        private System.DateTime birthDateField;
        
        private string emailField;
        
        private byte genderField;
        
        private int provinceField;
        
        private int cityField;
        
        private string addressField;
        
        private string postalCodeField;
        
        private System.DateTime additionalDateField;
        
        private string additionalTextField;
        
        private string descriptionsField;
        
        private System.DateTime createDateField;
        
        private int contactSortField;
        
        private byte contactStatusField;
        
        private double creditField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ContactID
        {
            get
            {
                return this.contactIDField;
            }
            set
            {
                this.contactIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Corporation
        {
            get
            {
                return this.corporationField;
            }
            set
            {
                this.corporationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NickName
        {
            get
            {
                return this.nickNameField;
            }
            set
            {
                this.nickNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MobileNumbers
        {
            get
            {
                return this.mobileNumbersField;
            }
            set
            {
                this.mobileNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PhoneNumbers
        {
            get
            {
                return this.phoneNumbersField;
            }
            set
            {
                this.phoneNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FaxNumbers
        {
            get
            {
                return this.faxNumbersField;
            }
            set
            {
                this.faxNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public byte Gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int Province
        {
            get
            {
                return this.provinceField;
            }
            set
            {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public System.DateTime AdditionalDate
        {
            get
            {
                return this.additionalDateField;
            }
            set
            {
                this.additionalDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string AdditionalText
        {
            get
            {
                return this.additionalTextField;
            }
            set
            {
                this.additionalTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Descriptions
        {
            get
            {
                return this.descriptionsField;
            }
            set
            {
                this.descriptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public System.DateTime CreateDate
        {
            get
            {
                return this.createDateField;
            }
            set
            {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int ContactSort
        {
            get
            {
                return this.contactSortField;
            }
            set
            {
                this.contactSortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public byte ContactStatus
        {
            get
            {
                return this.contactStatusField;
            }
            set
            {
                this.contactStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public double Credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContactsByID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetContactsByIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int contactId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int status;
        
        public GetContactsByIDRequest()
        {
        }
        
        public GetContactsByIDRequest(string username, string password, int contactId, int status)
        {
            this.username = username;
            this.password = password;
            this.contactId = contactId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContactsByIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetContactsByIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ContactsWebService.ContactsBL GetContactsByIDResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int status;
        
        public GetContactsByIDResponse()
        {
        }
        
        public GetContactsByIDResponse(ContactsWebService.ContactsBL GetContactsByIDResult, int status)
        {
            this.GetContactsByIDResult = GetContactsByIDResult;
            this.status = status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ContactsSoapChannel : ContactsWebService.ContactsSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ContactsSoapClient : System.ServiceModel.ClientBase<ContactsWebService.ContactsSoap>, ContactsWebService.ContactsSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ContactsSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ContactsSoapClient.GetBindingForEndpoint(endpointConfiguration), ContactsSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContactsSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ContactsSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContactsSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ContactsSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContactsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> AddGroupAsync(string username, string password, string groupName, string Descriptions, bool showToChilds)
        {
            return base.Channel.AddGroupAsync(username, password, groupName, Descriptions, showToChilds);
        }
        
        public System.Threading.Tasks.Task<ContactsWebService.GroupsList[]> GetGroupsAsync(string username, string password)
        {
            return base.Channel.GetGroupsAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<int> AddContactAsync(
                    string username, 
                    string password, 
                    string groupIds, 
                    string firstname, 
                    string lastname, 
                    string nickname, 
                    string corporation, 
                    string mobilenumber, 
                    string phone, 
                    string fax, 
                    System.DateTime birthdate, 
                    string email, 
                    byte gender, 
                    int province, 
                    int city, 
                    string address, 
                    string postalCode, 
                    System.DateTime additionaldate, 
                    string additionaltext, 
                    string descriptions)
        {
            return base.Channel.AddContactAsync(username, password, groupIds, firstname, lastname, nickname, corporation, mobilenumber, phone, fax, birthdate, email, gender, province, city, address, postalCode, additionaldate, additionaltext, descriptions);
        }
        
        public System.Threading.Tasks.Task<ContactsWebService.GetContactsByIDResponse> GetContactsByIDAsync(ContactsWebService.GetContactsByIDRequest request)
        {
            return base.Channel.GetContactsByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ContactsWebService.ContactsGridList[]> GetContactsAsync(string username, string password, int groupId, string keyword, int from, int count)
        {
            return base.Channel.GetContactsAsync(username, password, groupId, keyword, from, count);
        }
        
        public System.Threading.Tasks.Task<ContactsWebService.ContactEventBL[]> GetContactEventsAsync(string username, string password, int contactId)
        {
            return base.Channel.GetContactEventsAsync(username, password, contactId);
        }
        
        public System.Threading.Tasks.Task<int> CheckMobileExistInContactAsync(string username, string password, string mobileNumber)
        {
            return base.Channel.CheckMobileExistInContactAsync(username, password, mobileNumber);
        }
        
        public System.Threading.Tasks.Task<int> ChangeContactAsync(
                    string username, 
                    string password, 
                    int contactId, 
                    string mobilenumber, 
                    string firstname, 
                    string lastname, 
                    string nickname, 
                    string corporation, 
                    string phone, 
                    string fax, 
                    string email, 
                    byte gender, 
                    int province, 
                    int city, 
                    string address, 
                    string postalCode, 
                    string additionaltext, 
                    string descriptions, 
                    int contactStatus)
        {
            return base.Channel.ChangeContactAsync(username, password, contactId, mobilenumber, firstname, lastname, nickname, corporation, phone, fax, email, gender, province, city, address, postalCode, additionaltext, descriptions, contactStatus);
        }
        
        public System.Threading.Tasks.Task<int> RemoveContactAsync(string username, string password, string mobilenumber)
        {
            return base.Channel.RemoveContactAsync(username, password, mobilenumber);
        }
        
        public System.Threading.Tasks.Task<int> RemoveContact2Async(string username, string password, int contactId, int groupId)
        {
            return base.Channel.RemoveContact2Async(username, password, contactId, groupId);
        }
        
        public System.Threading.Tasks.Task<int> RemoveContactByContactIDAsync(string username, string password, int contactId)
        {
            return base.Channel.RemoveContactByContactIDAsync(username, password, contactId);
        }
        
        public System.Threading.Tasks.Task<int> ChangeGroupAsync(string username, string password, int groupId, string groupName, string Descriptions, bool showToChilds, byte groupStatus)
        {
            return base.Channel.ChangeGroupAsync(username, password, groupId, groupName, Descriptions, showToChilds, groupStatus);
        }
        
        public System.Threading.Tasks.Task<int> RemoveGroupAsync(string username, string password, int groupId)
        {
            return base.Channel.RemoveGroupAsync(username, password, groupId);
        }
        
        public System.Threading.Tasks.Task<int> AddContactEventsAsync(string username, string password, int contactId, string eventName, byte eventType, System.DateTime eventDate)
        {
            return base.Channel.AddContactEventsAsync(username, password, contactId, eventName, eventType, eventDate);
        }
        
        public System.Threading.Tasks.Task<int> MergeGroupsAsync(string username, string password, int originGroupId, int destinationGroupId, bool deleteOriginGroup)
        {
            return base.Channel.MergeGroupsAsync(username, password, originGroupId, destinationGroupId, deleteOriginGroup);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ContactsSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ContactsSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ContactsSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://api.payamak-panel.com/post/contacts.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ContactsSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://api.payamak-panel.com/post/contacts.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ContactsSoap,
            
            ContactsSoap12,
        }
    }
}
