//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionsWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ActionsWebService.ActionsSoap")]
    public interface ActionsSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBranchs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<ActionsWebService.Branchs[]> GetBranchsAsync(string username, string password, int owner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBranch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> AddBranchAsync(string username, string password, string branchName, int owner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> AddNumberAsync(string username, string password, int branchId, string[] mobileNumbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveBranch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> RemoveBranchAsync(string username, string password, int branchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBulkCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> GetBulkCountAsync(string username, string password, int branch, string rangeFrom, string rangeTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBulk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> AddBulkAsync(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, System.DateTime DateToSend, int requestCount, int rowFrom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBulk2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> AddBulk2Async(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, string DateToSend, int requestCount, int rowFrom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewBulk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> AddNewBulkAsync(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, System.DateTime DateToSend, int requestCount, int rowFrom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBulkReceptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<ActionsWebService.BulkReceptions[]> GetBulkReceptionsAsync(string username, string password, int bulkId, int fromRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBulkDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> UpdateBulkDeliveryAsync(string username, string password, int bulkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesReceptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<ActionsWebService.MsgReceptions[]> GetMessagesReceptionsAsync(string username, string password, long msgId, int fromRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveBulk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> RemoveBulkAsync(string username, string password, int bulkId);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBulkStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<ActionsWebService.GetBulkStatusResponse> GetBulkStatusAsync(ActionsWebService.GetBulkStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalSent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> GetTotalSentAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTodaySent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> GetTodaySentAsync(string username, string password);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMultipleSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<ActionsWebService.SendMultipleSMSResponse> SendMultipleSMSAsync(ActionsWebService.SendMultipleSMSRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMultipleSMS2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<ActionsWebService.SendMultipleSMS2Response> SendMultipleSMS2Async(ActionsWebService.SendMultipleSMS2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMultipleSMS3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<long[]> SendMultipleSMS3Async(string username, string password, string[] to, string from, string[] text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMultipleSMS3Deliveries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int[]> GetMultipleSMS3DeliveriesAsync(long[] Id, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsQueue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<ActionsWebService.SmsQueueList> GetSmsQueueAsync(string username, string password, long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBulk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<ActionsWebService.BulkGridList[]> GetBulkAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSendBulk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<ActionsWebService.BulkGridList[]> GetSendBulkAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMobileCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<int> GetMobileCountAsync(string username, string password, int branch, string rangeFrom, string rangeTo);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Branchs
    {
        
        private int branchIDField;
        
        private int numberCountField;
        
        private int branchOwnerField;
        
        private string branchNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int BranchID
        {
            get
            {
                return this.branchIDField;
            }
            set
            {
                this.branchIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int NumberCount
        {
            get
            {
                return this.numberCountField;
            }
            set
            {
                this.numberCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int BranchOwner
        {
            get
            {
                return this.branchOwnerField;
            }
            set
            {
                this.branchOwnerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BranchName
        {
            get
            {
                return this.branchNameField;
            }
            set
            {
                this.branchNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BulksBL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BulkGridList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseBL
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BulkGridList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BulksBL : BaseBL
    {
        
        private int bulkIDField;
        
        private int userIDField;
        
        private double tariffField;
        
        private int branchIDField;
        
        private System.Nullable<System.Guid> batchIDField;
        
        private byte bulkTypeField;
        
        private byte sendTypeField;
        
        private string titleField;
        
        private string bodyField;
        
        private int bodyPartsField;
        
        private int senderField;
        
        private string rangeFromField;
        
        private string rangeToField;
        
        private int rowFromField;
        
        private byte numberRuleField;
        
        private string numberTextField;
        
        private System.DateTime scheduleDateField;
        
        private System.Nullable<System.DateTime> sentDateField;
        
        private int requestCountField;
        
        private int sentCountField;
        
        private int failedCountField;
        
        private byte periodField;
        
        private byte sendStatusField;
        
        private string descriptionsField;
        
        private string errorLogField;
        
        private byte bulkStatusField;
        
        private double creditField;
        
        private bool isMoneyBackField;
        
        private int moneyBackCountField;
        
        private int moneyBackLevelField;
        
        private string gIDField;
        
        private string cGIDField;
        
        private string fromGIDField;
        
        private bool notBlackListField;
        
        private bool notifySMSField;
        
        private string mobileNumberNotifyField;
        
        private System.Nullable<int> irancellBackCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int BulkID
        {
            get
            {
                return this.bulkIDField;
            }
            set
            {
                this.bulkIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Tariff
        {
            get
            {
                return this.tariffField;
            }
            set
            {
                this.tariffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int BranchID
        {
            get
            {
                return this.branchIDField;
            }
            set
            {
                this.branchIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.Guid> BatchID
        {
            get
            {
                return this.batchIDField;
            }
            set
            {
                this.batchIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public byte BulkType
        {
            get
            {
                return this.bulkTypeField;
            }
            set
            {
                this.bulkTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public byte SendType
        {
            get
            {
                return this.sendTypeField;
            }
            set
            {
                this.sendTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int BodyParts
        {
            get
            {
                return this.bodyPartsField;
            }
            set
            {
                this.bodyPartsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int Sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string RangeFrom
        {
            get
            {
                return this.rangeFromField;
            }
            set
            {
                this.rangeFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string RangeTo
        {
            get
            {
                return this.rangeToField;
            }
            set
            {
                this.rangeToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int RowFrom
        {
            get
            {
                return this.rowFromField;
            }
            set
            {
                this.rowFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public byte NumberRule
        {
            get
            {
                return this.numberRuleField;
            }
            set
            {
                this.numberRuleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string NumberText
        {
            get
            {
                return this.numberTextField;
            }
            set
            {
                this.numberTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public System.DateTime ScheduleDate
        {
            get
            {
                return this.scheduleDateField;
            }
            set
            {
                this.scheduleDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<System.DateTime> SentDate
        {
            get
            {
                return this.sentDateField;
            }
            set
            {
                this.sentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int RequestCount
        {
            get
            {
                return this.requestCountField;
            }
            set
            {
                this.requestCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int SentCount
        {
            get
            {
                return this.sentCountField;
            }
            set
            {
                this.sentCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int FailedCount
        {
            get
            {
                return this.failedCountField;
            }
            set
            {
                this.failedCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public byte Period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public byte SendStatus
        {
            get
            {
                return this.sendStatusField;
            }
            set
            {
                this.sendStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Descriptions
        {
            get
            {
                return this.descriptionsField;
            }
            set
            {
                this.descriptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string ErrorLog
        {
            get
            {
                return this.errorLogField;
            }
            set
            {
                this.errorLogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public byte BulkStatus
        {
            get
            {
                return this.bulkStatusField;
            }
            set
            {
                this.bulkStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public double Credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public bool IsMoneyBack
        {
            get
            {
                return this.isMoneyBackField;
            }
            set
            {
                this.isMoneyBackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public int MoneyBackCount
        {
            get
            {
                return this.moneyBackCountField;
            }
            set
            {
                this.moneyBackCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public int MoneyBackLevel
        {
            get
            {
                return this.moneyBackLevelField;
            }
            set
            {
                this.moneyBackLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string GID
        {
            get
            {
                return this.gIDField;
            }
            set
            {
                this.gIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string CGID
        {
            get
            {
                return this.cGIDField;
            }
            set
            {
                this.cGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string FromGID
        {
            get
            {
                return this.fromGIDField;
            }
            set
            {
                this.fromGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public bool NotBlackList
        {
            get
            {
                return this.notBlackListField;
            }
            set
            {
                this.notBlackListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public bool NotifySMS
        {
            get
            {
                return this.notifySMSField;
            }
            set
            {
                this.notifySMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string MobileNumberNotify
        {
            get
            {
                return this.mobileNumberNotifyField;
            }
            set
            {
                this.mobileNumberNotifyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public System.Nullable<int> IrancellBackCount
        {
            get
            {
                return this.irancellBackCountField;
            }
            set
            {
                this.irancellBackCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BulkGridList : BulksBL
    {
        
        private string branchNameField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BranchName
        {
            get
            {
                return this.branchNameField;
            }
            set
            {
                this.branchNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SmsQueueList
    {
        
        private long idField;
        
        private int senderField;
        
        private string bodyField;
        
        private string receiverField;
        
        private System.DateTime insertDateField;
        
        private System.Nullable<System.DateTime> fetchDateField;
        
        private byte statusField;
        
        private System.Nullable<long> recIDField;
        
        private System.Nullable<int> deliveryStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Receiver
        {
            get
            {
                return this.receiverField;
            }
            set
            {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime InsertDate
        {
            get
            {
                return this.insertDateField;
            }
            set
            {
                this.insertDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> FetchDate
        {
            get
            {
                return this.fetchDateField;
            }
            set
            {
                this.fetchDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public byte Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<long> RecID
        {
            get
            {
                return this.recIDField;
            }
            set
            {
                this.recIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> DeliveryStatus
        {
            get
            {
                return this.deliveryStatusField;
            }
            set
            {
                this.deliveryStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgReceptions
    {
        
        private string recNumberField;
        
        private string sendDateField;
        
        private string recStatusField;
        
        private string deliveryStatusField;
        
        private string recIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RecNumber
        {
            get
            {
                return this.recNumberField;
            }
            set
            {
                this.recNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SendDate
        {
            get
            {
                return this.sendDateField;
            }
            set
            {
                this.sendDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RecStatus
        {
            get
            {
                return this.recStatusField;
            }
            set
            {
                this.recStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DeliveryStatus
        {
            get
            {
                return this.deliveryStatusField;
            }
            set
            {
                this.deliveryStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RecID
        {
            get
            {
                return this.recIDField;
            }
            set
            {
                this.recIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BulkReceptions
    {
        
        private string recNumberField;
        
        private string sendDateField;
        
        private string recStatusField;
        
        private string deliveryStatusField;
        
        private string opIDField;
        
        private string bulkIDField;
        
        private string recIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RecNumber
        {
            get
            {
                return this.recNumberField;
            }
            set
            {
                this.recNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SendDate
        {
            get
            {
                return this.sendDateField;
            }
            set
            {
                this.sendDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RecStatus
        {
            get
            {
                return this.recStatusField;
            }
            set
            {
                this.recStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DeliveryStatus
        {
            get
            {
                return this.deliveryStatusField;
            }
            set
            {
                this.deliveryStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OpID
        {
            get
            {
                return this.opIDField;
            }
            set
            {
                this.opIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BulkID
        {
            get
            {
                return this.bulkIDField;
            }
            set
            {
                this.bulkIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RecID
        {
            get
            {
                return this.recIDField;
            }
            set
            {
                this.recIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBulkStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBulkStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int bulkId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int sent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int failed;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        public GetBulkStatusRequest()
        {
        }
        
        public GetBulkStatusRequest(string username, string password, int bulkId, int sent, int failed, byte status)
        {
            this.username = username;
            this.password = password;
            this.bulkId = bulkId;
            this.sent = sent;
            this.failed = failed;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBulkStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBulkStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetBulkStatusResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int sent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int failed;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public byte status;
        
        public GetBulkStatusResponse()
        {
        }
        
        public GetBulkStatusResponse(int GetBulkStatusResult, int sent, int failed, byte status)
        {
            this.GetBulkStatusResult = GetBulkStatusResult;
            this.sent = sent;
            this.failed = failed;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMultipleSMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMultipleSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string[] text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isflash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string udh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendMultipleSMSRequest()
        {
        }
        
        public SendMultipleSMSRequest(string username, string password, string[] to, string from, string[] text, bool isflash, string udh, long[] recId, byte[] status)
        {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMultipleSMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMultipleSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int[] SendMultipleSMSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendMultipleSMSResponse()
        {
        }
        
        public SendMultipleSMSResponse(int[] SendMultipleSMSResult, long[] recId, byte[] status)
        {
            this.SendMultipleSMSResult = SendMultipleSMSResult;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMultipleSMS2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMultipleSMS2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string[] text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isflash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string udh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendMultipleSMS2Request()
        {
        }
        
        public SendMultipleSMS2Request(string username, string password, string[] to, string[] from, string[] text, bool isflash, string udh, long[] recId, byte[] status)
        {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMultipleSMS2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMultipleSMS2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int[] SendMultipleSMS2Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendMultipleSMS2Response()
        {
        }
        
        public SendMultipleSMS2Response(int[] SendMultipleSMS2Result, long[] recId, byte[] status)
        {
            this.SendMultipleSMS2Result = SendMultipleSMS2Result;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ActionsSoapChannel : ActionsWebService.ActionsSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ActionsSoapClient : System.ServiceModel.ClientBase<ActionsWebService.ActionsSoap>, ActionsWebService.ActionsSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ActionsSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ActionsSoapClient.GetBindingForEndpoint(endpointConfiguration), ActionsSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ActionsSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ActionsSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ActionsSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ActionsSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ActionsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ActionsWebService.Branchs[]> GetBranchsAsync(string username, string password, int owner)
        {
            return base.Channel.GetBranchsAsync(username, password, owner);
        }
        
        public System.Threading.Tasks.Task<int> AddBranchAsync(string username, string password, string branchName, int owner)
        {
            return base.Channel.AddBranchAsync(username, password, branchName, owner);
        }
        
        public System.Threading.Tasks.Task<int> AddNumberAsync(string username, string password, int branchId, string[] mobileNumbers)
        {
            return base.Channel.AddNumberAsync(username, password, branchId, mobileNumbers);
        }
        
        public System.Threading.Tasks.Task<int> RemoveBranchAsync(string username, string password, int branchId)
        {
            return base.Channel.RemoveBranchAsync(username, password, branchId);
        }
        
        public System.Threading.Tasks.Task<int> GetBulkCountAsync(string username, string password, int branch, string rangeFrom, string rangeTo)
        {
            return base.Channel.GetBulkCountAsync(username, password, branch, rangeFrom, rangeTo);
        }
        
        public System.Threading.Tasks.Task<int> AddBulkAsync(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, System.DateTime DateToSend, int requestCount, int rowFrom)
        {
            return base.Channel.AddBulkAsync(username, password, from, branch, bulkType, title, message, rangeFrom, rangeTo, DateToSend, requestCount, rowFrom);
        }
        
        public System.Threading.Tasks.Task<int> AddBulk2Async(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, string DateToSend, int requestCount, int rowFrom)
        {
            return base.Channel.AddBulk2Async(username, password, from, branch, bulkType, title, message, rangeFrom, rangeTo, DateToSend, requestCount, rowFrom);
        }
        
        public System.Threading.Tasks.Task<int> AddNewBulkAsync(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, System.DateTime DateToSend, int requestCount, int rowFrom)
        {
            return base.Channel.AddNewBulkAsync(username, password, from, branch, bulkType, title, message, rangeFrom, rangeTo, DateToSend, requestCount, rowFrom);
        }
        
        public System.Threading.Tasks.Task<ActionsWebService.BulkReceptions[]> GetBulkReceptionsAsync(string username, string password, int bulkId, int fromRows)
        {
            return base.Channel.GetBulkReceptionsAsync(username, password, bulkId, fromRows);
        }
        
        public System.Threading.Tasks.Task<int> UpdateBulkDeliveryAsync(string username, string password, int bulkId)
        {
            return base.Channel.UpdateBulkDeliveryAsync(username, password, bulkId);
        }
        
        public System.Threading.Tasks.Task<ActionsWebService.MsgReceptions[]> GetMessagesReceptionsAsync(string username, string password, long msgId, int fromRows)
        {
            return base.Channel.GetMessagesReceptionsAsync(username, password, msgId, fromRows);
        }
        
        public System.Threading.Tasks.Task<int> RemoveBulkAsync(string username, string password, int bulkId)
        {
            return base.Channel.RemoveBulkAsync(username, password, bulkId);
        }
        
        public System.Threading.Tasks.Task<ActionsWebService.GetBulkStatusResponse> GetBulkStatusAsync(ActionsWebService.GetBulkStatusRequest request)
        {
            return base.Channel.GetBulkStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<int> GetTotalSentAsync(string username, string password)
        {
            return base.Channel.GetTotalSentAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<int> GetTodaySentAsync(string username, string password)
        {
            return base.Channel.GetTodaySentAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<ActionsWebService.SendMultipleSMSResponse> SendMultipleSMSAsync(ActionsWebService.SendMultipleSMSRequest request)
        {
            return base.Channel.SendMultipleSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ActionsWebService.SendMultipleSMS2Response> SendMultipleSMS2Async(ActionsWebService.SendMultipleSMS2Request request)
        {
            return base.Channel.SendMultipleSMS2Async(request);
        }
        
        public System.Threading.Tasks.Task<long[]> SendMultipleSMS3Async(string username, string password, string[] to, string from, string[] text)
        {
            return base.Channel.SendMultipleSMS3Async(username, password, to, from, text);
        }
        
        public System.Threading.Tasks.Task<int[]> GetMultipleSMS3DeliveriesAsync(long[] Id, string username, string password)
        {
            return base.Channel.GetMultipleSMS3DeliveriesAsync(Id, username, password);
        }
        
        public System.Threading.Tasks.Task<ActionsWebService.SmsQueueList> GetSmsQueueAsync(string username, string password, long Id)
        {
            return base.Channel.GetSmsQueueAsync(username, password, Id);
        }
        
        public System.Threading.Tasks.Task<ActionsWebService.BulkGridList[]> GetBulkAsync(string username, string password)
        {
            return base.Channel.GetBulkAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<ActionsWebService.BulkGridList[]> GetSendBulkAsync(string username, string password)
        {
            return base.Channel.GetSendBulkAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<int> GetMobileCountAsync(string username, string password, int branch, string rangeFrom, string rangeTo)
        {
            return base.Channel.GetMobileCountAsync(username, password, branch, rangeFrom, rangeTo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ActionsSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ActionsSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ActionsSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://api.payamak-panel.com/post/actions.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ActionsSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://api.payamak-panel.com/post/actions.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ActionsSoap,
            
            ActionsSoap12,
        }
    }
}
